name: Build and deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build site with Hugo
      env:
        HUGO_BASEURL: https://vahidpeiman.github.io/VP_KKB/
      run: |
        # اگر سورس سایت شما در ریشه مخزن است:
        hugo --minify
        # اگر سورس سایت در یک زیرپوشه است (مثل ./site یا ./docs)، خط زیر را فعال کنید:
        # hugo --minify --source ./docs

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
